image: node:latest

cache:
  paths:
  - node_modules/

test:
  script:
   - npm install
   - ./node_modules/.bin/mocha --timeout 10000 --compilers js:babel-core/register --reporter spec --bail --check-leaks --colors --require babel-polyfill
