image: node:latest

cache:
  paths:
  - node_modules/

test:
  script:
   - npm install
   - ./node_modules/.bin/mocha --timeout 10000 --compilers js:babel-core/register --reporter spec --bail --check-leaks --colors --require babel-polyfill
   
updatecov:
  script:
    - npm install
    - npm install codecov
    - babel-node ./node_modules/.bin/babel-istanbul cover ./node_modules/.bin/_mocha test && codecov -t 1bfb0639-fb2f-4615-8b60-1318ba0379fe

updatedoc:
  script:
   - npm install
   - npm install esdoc
   - esdoc
   - cd doc/
   - git add .
   - git commit -m "Documentation update"
   - git push heroku master
